#!/usr/bin/env bash
# Rawana - UserBot
# Copyright (C) 2021-2022 TeamRawana
#
# This file is a part of < https://github.com/Rawana-Developers/Rawana-User-Bot/ >
# PLease read the GNU Affero General Public License in <https://github.com/Rawana-Developers/Rawana-User-Bot/blob/main/LICENSE>.

bash resources/session/session.sh
