#!/usr/bin/env bash
# Rawana - UserBot
# Copyright (C) 2021-2022 TeamRawana
#
# This file is a part of < https://github.com/Rawana-Developers/Rawana-User-Bot/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Rawana-Developers/Rawana-User-Bot/blob/main/LICENSE/>.


echo "
           ΞΞΞΞΞΞΞΞΞΞΞ         ΞΞΞΞΞΞ       ΞΞ             ΞΞ            ΞΞ     ΞΞΞΞΞΞ       ΞΞΞΞ       ΞΞ     ΞΞΞΞΞ
           ΞΞ       ΞΞ        ΞΞ    ΞΞ       ΞΞ           ΞΞΞΞ          ΞΞ     ΞΞ    ΞΞ      ΞΞ ΞΞ      ΞΞ    ΞΞ   ΞΞ
           ΞΞ       ΞΞ       ΞΞ      ΞΞ       ΞΞ         ΞΞ  ΞΞ        ΞΞ     ΞΞ      ΞΞ     ΞΞ  ΞΞ     ΞΞ   ΞΞ     ΞΞ
           ΞΞΞΞΞΞΞΞΞΞΞ      ΞΞ        ΞΞ       ΞΞ       ΞΞ    ΞΞ      ΞΞ     ΞΞ        ΞΞ    ΞΞ   ΞΞ    ΞΞ  ΞΞΞΞΞΞΞΞΞΞΞ 
           ΞΞ  ΞΞ           ΞΞ ΞΞΞΞΞΞ ΞΞ        ΞΞ     ΞΞ      ΞΞ    ΞΞ      ΞΞ ΞΞΞΞΞΞ ΞΞ    ΞΞ    ΞΞ   ΞΞ  ΞΞ       ΞΞ
           ΞΞ   ΞΞ          ΞΞ        ΞΞ         ΞΞ  ΞΞ         ΞΞ  ΞΞ       ΞΞ        ΞΞ    ΞΞ     ΞΞ  ΞΞ  ΞΞ       ΞΞ 
           ΞΞ    ΞΞ         ΞΞ        ΞΞ          ΞΞΞΞ           ΞΞΞΞ        ΞΞ        ΞΞ    ΞΞ      ΞΞ ΞΞ  ΞΞ       ΞΞ 
           ΞΞ     ΞΞ        ΞΞ        ΞΞ           ΞΞ             ΞΞ         ΞΞ        ΞΞ    ΞΞ       ΞΞΞΞ  ΞΞ       ΞΞ

      Visit @Rawana_Developers for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyRawana ; fi
