blank_issues_enabled: true
contact_links:
  - name: Rawana Support
    url: https://t.me/Rawana_Developers
    about: Please drop your doubts or queries there for an immediate response.
  - name: Updert
    url: https://t.me/Rawana_Bot_Developers
    about: This UserBot Updert
